#!/usr/bin/env python3
"""
Генерирует version script для PyInstaller из build-конфига.

Вызывается из scripts/build.bat и выводит переменные KEY=VALUE
для формирования аргументов PyInstaller.
"""

import json
import pprint
import sys
from datetime import datetime
from pathlib import Path


def _project_dir_from_build_config(build_json: Path) -> Path:
    if build_json.parent.name.lower() == "config" and (build_json.parent.parent / "src").exists():
        return build_json.parent.parent
    return Path.cwd()


def _write_bat_var(f, name: str, value: str) -> None:
    escaped = value.replace('"', '\\"')
    f.write(f'set "{name}={escaped}"\n')


def main():
    if len(sys.argv) < 3:
        print("Usage: _gen_version.py <build-config.json> <output_dir>")
        sys.exit(1)

    build_json = Path(sys.argv[1]).resolve()
    output_dir = Path(sys.argv[2])

    if not build_json.exists():
        print(f"ERROR: {build_json} not found")
        sys.exit(1)

    # Читаем конфиг сборки
    with open(build_json, encoding="utf-8") as f:
        cfg = json.load(f)

    project_dir = _project_dir_from_build_config(build_json)

    # Разбираем параметры
    output_exe = cfg.get("outputExe", "jenkins-agent.exe")
    exe_name = output_exe.replace(".exe", "")
    version = cfg.get("version", "1.0.0.0")
    title = cfg.get("title", "Jenkins Agent Launcher")
    company = cfg.get("company", "Jenkins Agent Launcher Contributors")
    year = datetime.now().year

    # Разбираем версию на части
    parts = version.split(".")
    while len(parts) < 4:
        parts.append("0")
    try:
        vmjr, vmnr, vrel, vbld = [int(p) for p in parts[:4]]
    except ValueError:
        vmjr = vmnr = vrel = vbld = 0

    # Иконка
    icon_rel = cfg.get("iconPath", "")
    icon_full = project_dir / icon_rel if icon_rel else Path()
    icon_exists = icon_full.exists() if icon_rel else False
    if icon_rel and not icon_exists:
        print(f"ERROR: iconPath not found: {icon_full}")
        sys.exit(1)

    # Режим окна
    no_console = cfg.get("noConsole", True)

    # Генерируем version script
    ver_script = output_dir / "_version.py"
    output_dir.mkdir(parents=True, exist_ok=True)

    script_content = f"""# Auto-generated by _gen_version.py
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({vmjr}, {vmnr}, {vrel}, {vbld}),
    prodvers=({vmjr}, {vmnr}, {vrel}, {vbld}),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)),
  kids=[
    StringFileInfo([
      StringTable(
        u'041904B0',
        [StringStruct(u'CompanyName', u'{company}'),
         StringStruct(u'FileDescription', u'{title}'),
         StringStruct(u'FileVersion', u'{version}'),
         StringStruct(u'InternalName', u'{exe_name}.exe'),
         StringStruct(u'LegalCopyright', u'\\u00A9 {year} {company}'),
         StringStruct(u'OriginalFilename', u'{exe_name}.exe'),
         StringStruct(u'ProductName', u'{title}'),
         StringStruct(u'ProductVersion', u'{version}')])
    ]),
    VarFileInfo([VarStruct(u'Translation', [1049, 1200])])
  ]
)
"""

    with open(ver_script, "w", encoding="utf-8") as f:
        f.write(script_content)

    # Пишем .bat-файл с переменными (надёжнее чем вывод в stdout)
    vars_bat = output_dir / "_build_vars.bat"
    runtime_info = project_dir / "src" / "_build_info.py"
    runtime_content = (
        "# Auto-generated by scripts/_gen_version.py during packaging.\n"
        "# Do not edit by hand.\n\n"
        f"BUILD_INFO = {pprint.pformat(cfg, width=100, sort_dicts=True)}\n"
    )
    runtime_info.parent.mkdir(parents=True, exist_ok=True)
    runtime_info.write_text(runtime_content, encoding="utf-8")

    with open(vars_bat, "w", encoding="utf-8") as f:
        _write_bat_var(f, "OUTPUT_EXE", output_exe)
        _write_bat_var(f, "EXE_NAME", exe_name)
        _write_bat_var(f, "VER_SCRIPT", str(ver_script))
        _write_bat_var(f, "RUNTIME_INFO", str(runtime_info))
        _write_bat_var(f, "ICON", str(icon_full) if icon_exists else "")
        _write_bat_var(f, "NOCONSOLE", "true" if no_console else "false")

    vars_json = output_dir / "_build_vars.json"
    vars_json.write_text(
        json.dumps(
            {
                "outputExe": output_exe,
                "exeName": exe_name,
                "versionScript": str(ver_script),
                "runtimeInfo": str(runtime_info),
                "icon": str(icon_full) if icon_exists else "",
                "noConsole": no_console,
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )

    print(f"OK: {ver_script}")


if __name__ == "__main__":
    main()
